# Generated by Django 4.1.7 on 2023-03-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation',
        ),
    ]
